---
database_name: timeoverflow_staging
rails_environment: staging

sys_admins:
  - name: enrico
    ssh_key: "../pub_keys/enrico.pub"
    state: present
  - name: dani
    ssh_key: "../pub_keys/dani.pub"
    state: present
  - name: pau
    ssh_key: "../pub_keys/pau.pub"
    state: present
  - name: maxim
    ssh_key: "../pub_keys/maxim.pub"
    state: present

developers:
  - name: sergi
    ssh_key: "../pub_keys/sergi.pub"
    state: present

nginx:
  server_name: "staging.timeoverflow.org"
