sudo: required
dist: bionic
language: python
python: 3.7.4

jobs:
  include:
    - stage: lint
      script: ansible-lint playbooks/*.yml
    - stage: lint
      script: yamllint **/*.yml
    - stage: provision
      script:
        - openssl aes-256-cbc -K $encrypted_8208c68d3911_key -iv $encrypted_8208c68d3911_iv
          -in travis.enc -out travis -d
        - eval "$(ssh-agent -s)"
        - chmod 600 travis
        - ssh-add travis
        - ansible-galaxy install -r requirements.yml
        - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook playbooks/sys_admins.yml --limit=ci_server
        - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook playbooks/provision.yml --limit=ci_server
