---
- hosts: timeoverflow-dev
  become: yes
  roles:
    - common
    - role: zzet.rbenv
      rbenv_users:
        - ubuntu
    - database
    - { role: vendor/ansible-elasticsearch, es_instance_name: 'elasticsearch' }

  vars_files:
    - secrets/development.yml
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
    database_name: timeoverflow_development
    database_user: timeoverflow
    rails_environment: development
    rbenv:
      env: user
      version: v1.0.0
      ruby_version: 2.3.0
