- src: coopdevs.sys-admins-role
  version: v0.0.2
- src: geerlingguy.security
  version: 1.8.1
- src: zzet.rbenv
  version: 3.4.3
- src: geerlingguy.postgresql
  version: 2.0.0
- src: jdauphant.nginx
  version: v2.21.2
- src: coopdevs.certbot_nginx
  version: 0.0.4
- src: geerlingguy.redis
  version: 1.6.0
- src: coopdevs.backups_role
  version: v1.2.1
