- src: geerlingguy.security
  version: 1.5.0
- src: zzet.rbenv
  version: 3.4.2
- src: geerlingguy.postgresql
  version: 1.4.5
- src: elastic.elasticsearch
  version: 6.6.0
- src: jdauphant.nginx
  version: v2.21.2
- src: coopdevs.certbot_nginx
  version: 0.0.3
- src: DavidWittman.redis
  version: 1.2.5
