---
- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ database_name }}"
    encoding: UTF-8
    lc_collate: es_ES.UTF-8
    lc_ctype: es_ES.UTF-8
    template: template0
    state: present

- name: Add extensions to DB
  become_user: postgres
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ database_name }}"
  with_items:
    - plpgsql
    - hstore
    - pg_trgm

- name: Create dabase user
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ database_name }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    state: present
