---
- import_role:
    name: vendor/geerlingguy.postgresql
  vars:
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: "{{ database_user }}", auth_method: peer }
    postgresql_locales:
      - 'es_ES.UTF-8'

- include_role:
    name: geerlingguy.postgresql
    tasks_from: users
  vars:
    postgresql_users:
      - name: "{{ database_user }}"
        role_attr_flags: "{{ database_role_attributes }}"

- include_role:
    name: geerlingguy.postgresql
    tasks_from: databases
  vars:
    postgresql_databases:
      - name: "{{ database_name }}"
        owner: "{{ database_user }}"
        lc_collate: 'es_ES.UTF-8'
        lc_ctype: 'es_ES.UTF-8'

- import_tasks: create_extensions.yml
