---
database_name: timeoverflow_development
rails_environment: development
database_role_attributes: SUPERUSER

development_user: "{{ lookup('env', 'USER') }}"

sys_admins:
  - name: enrico
    ssh_key: "../pub_keys/enrico.pub"
    state: present
  - name: daniel
    ssh_key: "../pub_keys/dani.pub"
    state: present
  - name: pau
    ssh_key: "../pub_keys/pau.pub"
    state: present
  - name: travis
    ssh_key: "../pub_keys/travis.pub"
    state: present

developers: []

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: true

# Set super admins email addresses
superadmins: 'admin@timeoverflow.org'

backups_role_enabled: false
