---
database_name: timeoverflow_development
rails_environment: development
database_role_attributes: SUPERUSER
database_password: OZM+Ey389Rk=

development_user: "{{ lookup('env', 'USER') }}"

sys_admins:
  - name: enrico
    ssh_key: "../pub_keys/enrico.pub"
    state: present
  - name: daniel
    ssh_key: "../pub_keys/dani.pub"
    state: present
  - name: pau
    ssh_key: "../pub_keys/pau.pub"
    state: present
  - name: travis
    ssh_key: "../pub_keys/travis.pub"
    state: present

developers: []

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: true

# Set super admins email addresses
superadmins: 'admin@timeoverflow.org'

backups_role_enabled: false

mailer_sender: info@timeoverflow.org
secret_token: 9JlwmB955Q24nH6mLhVlHDCy/7ju/rPgTXAn8TgPDoQyPOyLWmNqR5758lh/DUVDBPcOnpJlkYwFbXxvHr2hBBjsLhivNSX79uwG44cDIhfJBoQSYP5jlsmBWVrAF/oH+1d/0EArVjlTU6bdynhO4bbIlPIdPzABycsLI43wUj8=
smtp_username: ''
smtp_password: ''
rollbar_access_token: ''

aws_access_key_id: ''
aws_secret_access_key: ''
aws_bucket: ''
aws_region: ''
