---
database_name: timeoverflow_development
database_password: OZM+Ey389Rk=

rails_environment: development
database_role_attributes: SUPERUSER

development_user: "{{ lookup('env', 'USER') }}"

sys_admins:
  - name: timeoverflow
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present
  - name: "{{ development_user }}"
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present

developers: []

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: true

# Set super admins email addresses
superadmins: 'admin@timeoverflow.org'

backups_role_enabled: false

smtp_username: ''
smtp_password: ''
rollbar_access_token: ''

mailer_sender: info@timeoverflow.org
secret_token: 9JlwmB955Q24nH6mLhVlHDCy/7ju/rPgTXAn8TgPDoQyPOyLWmNqR5758lh/DUVDBPcOnpJ$

aws_access_key_id: ''
aws_secret_access_key: ''
aws_bucket: ''
aws_region: ''


logrotate_conf: |
      /var/www/timeoverflow/current/log/*.log {
             weekly
             rotate 20
             size 300M
             compress
             delaycompress
      }
