---
- name: Install base system packages
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
    - build-essential
    - ca-certificates
    - git
    - apt-transport-https
    - curl
    - wget

- name: Install NodeJS - needed by ExecJS, in turn needed by sass, coffeescript etc
  apt:
    name: nodejs
