---
- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"


- name: Create sudoers
  template:
    dest: /etc/sudoers.d/timeoverflow
    mode: 0440
    owner: root
    group: root
    src: sudoers.timeoverflow
    validate: "/usr/sbin/visudo -cf %s"


# - name: Allow timeoverflow to restart things
#   lineinfile:
#     dest: /etc/sudoers.d/timeoverflow
#     state: present
#     line: 'timeoverflow ALL=(ALL) NOPASSWD: systemctl timeoverflow *'
#     validate: 'visudo -cf %s'
