---
- name: Create `timeoverflow` user
  user:
    name: timeoverflow
    groups: timeoverflow
    group: timeoverflow
    append: yes
    state: present
    shell: /bin/bash

# We need to add this block at the beginning of `.bashrc` since
# it will exit if not running in interactive mode. The main reason
# is that Capistrano uses non interactive mode to connect via SSH.
- name: Load environment variables in bashrc for `timeoverflow` user
  blockinfile:
    path: /home/timeoverflow/.bashrc
    insertbefore: BOF
    block: |
      set -a
      [ -f /etc/default/timeoverflow ] && . /etc/default/timeoverflow
      set +a

- name: Create sudoers for `timeoverflow` user
  template:
    dest: /etc/sudoers.d/timeoverflow
    mode: 0440
    owner: root
    group: root
    src: sudoers.timeoverflow
    validate: "/usr/sbin/visudo -cf %s"

- name: Add system administrator SSH public keys to `timeoverflow` user
  authorized_key:
    user: timeoverflow
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ sys_admins }}"

- name: Add developers SSH public keys to `timeoverflow` user
  authorized_key:
    user: timeoverflow
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ developers }}"
