---
- name: Create `timeoverflow` user
  user:
    name: timeoverflow
    groups: timeoverflow
    group: timeoverflow
    append: yes
    state: present
    shell: /bin/bash

- name: Write bash_profile for `timeoverflow` user
  template:
    src: bash_profile
    dest: /home/timeoverflow/.bash_profile
    owner: timeoverflow
    group: timeoverflow
    mode: 0644

- name: Create sudoers for `timeoverflow` user
  template:
    dest: /etc/sudoers.d/timeoverflow
    mode: 0440
    owner: root
    group: root
    src: sudoers.timeoverflow
    validate: "/usr/sbin/visudo -cf %s"

- name: Add system administrator SSH public keys to `timeoverflow` user
  authorized_key:
    user: timeoverflow
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ sys_admins }}"

- name: Add developers SSH public keys to `timeoverflow` user
  authorized_key:
    user: timeoverflow
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ developers }}"
