---
- name: Add certbot repository
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present

- name: Install certbot
  package:
    name: letsencrypt
    state: present

- name: Install certbot-nginx plugin
  package:
    name: python-certbot-nginx
    state: present

- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ nginx.server_name }}/cert.pem
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist
  shell: "certbot certonly --nginx --email {{ letsencrypt.email }} --agree-tos -d {{ nginx.server_name }}"
  when: not letsencrypt_cert.stat.exists

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal
    job: "letsencrypt renew"
    minute: 30
    hour: 3
    user: root
