---
- name: Create systemd unit for timeoverflow unicorn
  template:
    src: unicorn_service.j2
    dest: /etc/systemd/system/timeoverflow.service
  register: timeoverflow_unit

- name: Reload systemd # noqa 503
  systemd:
    daemon_reload: yes
  when: timeoverflow_unit.changed

- name: Create crontab entries for scheduled job
  cron:
    name: send_recent_posts_to_online_members
    user: "{{ app_user }}"
    state: absent

- include_role:
    name: vendor/coopdevs.certbot_nginx

- include_role:
    name: vendor/coopdevs.certbot_nginx
    tasks_from: certificate.yml
  vars:
    letsencrypt_email: "{{ certificate_authority_email }}"
  with_items: "{{ certificate_domain_names }}"
  loop_control:
    loop_var: domain_name

- include_role:
    name: vendor/jdauphant.nginx
  vars:
    nginx_configs:
      upstream:
        - upstream app_server { server localhost:8080 fail_timeout=0; }
