---
- name: Create systemd unit for timeoverflow unicorn
  template:
    src: unicorn_service.j2
    dest: /etc/systemd/system/timeoverflow.service

- name: Create crontab entries for scheduled job
  cron:
    name: send_recent_posts_to_online_members
    user: timeoverflow
    weekday: 1
    hour: 9
    minute: 0
    state: present
    job: >
      "/bin/bash -l -c 'cd {{ current_path }} && bin/rails runner '\''OrganizationNotifierService.new(Organization.all).send_recent_posts_to_online_members'\'' >> log/cron_log.log 2>&1'" # noqa 204

- include_role:
    name: vendor/coopdevs.certbot_nginx

- include_role:
    name: vendor/coopdevs.certbot_nginx
    tasks_from: certificate.yml
  vars:
    letsencrypt_email: "{{ certificate_authority_email }}"
  with_items: "{{ certificate_domain_names }}"
  loop_control:
    loop_var: domain_name

- name: Remove old timeoverflow.conf nginx site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/timeoverflow.conf

- name: Remove old next.timeoverflow.conf nginx site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/next.timeoverflow.org

- include_role:
    name: vendor/jdauphant.nginx
  vars:
    nginx_configs:
      upstream:
        - upstream app_server { server localhost:8080 fail_timeout=0; }
