---
- hosts: timeoverflow
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      security_autoupdate_enabled: false
    - common
    - role: vendor/zzet.rbenv
      rbenv:
        env: user
        version: v1.1.1
        default_ruby: 2.3.0
        rubies:
          - version: 2.3.0
      rbenv_users:
        - timeoverflow
    - database
    - role: vendor/elastic.elasticsearch
      es_instance_name: timeoverflow
      es_heap_size: "512m"
    - role: webserver
      when: not development_environment
    - cacheserver
