---
- hosts: timeoverflow
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      vars:
        security_autoupdate_enabled: true
        security_autoupdate_blacklist:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - nodejs
          - nginx
          - certbot
          - python-certbot-nginx
          - memcached
    - role: common
    - role: vendor/zzet.rbenv
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.6.3
        rubies:
          - version: 2.6.3
      rbenv_users:
        - timeoverflow
      default_gems_file: ../files/custom-gems
    - role: vendor/geerlingguy.postgresql
      vars:
        postgresql_hba_entries:
          - { type: local, database: all, user: postgres, auth_method: peer }
          - { type: local, database: all, user: "{{ database_user }}", auth_method: peer }
        postgresql_locales:
          - 'es_ES.UTF-8'
        postgresql_users:
          - name: "{{ database_user }}"
            role_attr_flags: "{{ database_role_attributes }}"
        postgresql_databases:
          - name: "{{ database_name }}"
            owner: "{{ database_user }}"
            lc_collate: 'es_ES.UTF-8'
            lc_ctype: 'es_ES.UTF-8'
        postgresql_python_library: python3-psycopg2 # related to ansible_python_interpreter
    - role: vendor/elastic.elasticsearch
      es_instance_name: timeoverflow
      es_heap_size: "512m"
    - role: webserver
      when: not development_environment
    - role: cacheserver
    - role: geerlingguy.redis
    - role: background_jobs
    - role: coopdevs.backups_role
      when: backups_role_enabled
