---
- hosts: timeoverflow
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      vars:
        security_autoupdate_enabled: true
        security_autoupdate_blacklist:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - nodejs
          - nginx
          - certbot
          - python-certbot-nginx
    - role: common
    - role: vendor/zzet.rbenv
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.6.3
        rubies:
          - version: 2.6.3
      rbenv_users:
        - timeoverflow
      default_gems_file: ../files/custom-gems
    - role: database
    - role: elasticsearch
      tags: es
    - role: webserver
      when: not development_environment
      tags: webserver
    - role: cacheserver
    - role: geerlingguy.redis
    - role: background_jobs
    - role: coopdevs.backups_role
      when: backups_role_enabled
