---
- hosts: timeoverflow
  become: yes
  roles:
    - role: vendor/geerlingguy.security
      security_autoupdate_enabled: false
    - role: common
    - role: vendor/zzet.rbenv
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.6.3
        rubies:
          - version: 2.6.3
      rbenv_users:
        - timeoverflow
      default_gems_file: ../files/custom-gems
    - role: database
    - role: webserver
      when: not development_environment
    - role: cacheserver
    - role: DavidWittman.redis
      vars:
        redis_version: 4.0.9
        redis_verify_checksum: true
        redis_checksum: "sha256:df4f73bc318e2f9ffb2d169a922dec57ec7c73dd07bccf875695dbeecd5ec510"
        redis_as_service: false # Read NOTES in https://github.com/coopdevs/timeoverflow-provisioning/pull/47
        redis_bind: 127.0.0.1
    - role: background_jobs
