---
- name: Create systemd unit for Sidekiq
  template:
    src: sidekiq_service.j2
    dest: /etc/systemd/system/sidekiq.service
    mode: 0644

- name: Set Sidekiq to start at boot
  service:
    name: sidekiq
    enabled: yes
