---
# The used ubuntu images comes with /usr/bin/python linking to python2.7 and it
# takes precedence.
ansible_python_interpreter: /usr/bin/python3
database_user: timeoverflow

app_path: "/var/www/timeoverflow"
current_path: "{{ app_path }}/current"
app_user: "timeoverflow"
environment_file: "/etc/default/timeoverflow"

# Backups vars
backups_role_postgresql_enabled: true
backups_role_sudoers_enabled: true
backups_role_db_names: ["{{ database_name }}"]
backups_role_assets_paths: ["{{ current_path }}/public"]

nginx_sites:
  timeoverflow:
    template: timeoverflow.conf.j2
    server_name: "{{ inventory_hostname }}"
  timeoverflow_http:
    template: timeoverflow_http.conf.j2
    server_name: "{{ inventory_hostname }}"
